/* Copyright 2021 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "kb.h"

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/

__attribute__((weak)) void matrix_init_user(void) {
    setPinOutput(STA3);
    writePinHigh(STA3);
    setPinOutput(STA1);
    setPinOutput(KCLK);
    writePinHigh(KCLK);
}

__attribute__((weak)) void post_process_record_user(uint16_t keycode, keyrecord_t *record) {
	static int pressed = 0;

	if( record->event.pressed) {
		pressed++;
	} else {
		pressed--;
	}

	if( pressed > 0 ) {
		writePinHigh(F5);
	} else {
		writePinLow(F5);
	}
}


