/* Copyright 2021 REPLACE_WITH_YOUR_NAME
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#pragma once

#include "quantum.h"

__attribute__((weak)) void matrix_init_user(void);

void amikb_sendkey(unsigned char keycode, int press);
void amikb_wait_for_ack_resync_if_none(void);
void amikb_wait_for_ack_reset_if_none(long timeout);
void wait_for_amiga(long timeout);
void amikb_reset(void);
void hard_reset(void);
void init_timer(void);
void reset_timer(void);
unsigned long get_msec(void);

// ACLK == KCLK == F6
#define ACLK	6
#define ACLK_BIT	(1 << ACLK)

// ADATA == KDAT == F7
#define ADATA	7
#define ADATA_BIT	(1 << ADATA)

#define PIN_CTRL 3
#define CTRL_BIT	(1 << PIN_CTRL)
#define PIN_LAMI 6
#define LAMI_BIT	(1 << PIN_LAMI)
#define PIN_RAMI 2
#define RAMI_BIT	(1 << PIN_RAMI)

#define TIMEOUT_MSEC 143
#define RESET_WARNING_MSEC 250
#define RESET_MSEC 500
#define RESET_WARNING_FULL_MSEC 10000


/*
 * STA3  STA2  STA1  KDAT  KCLK  VCC
 *  F3    F4    F5    F7    F6
 */

#define STA3 F3
#define STA2 F4
#define STA1 F5
#define KDAT F7
#define KCLK F6

#define LAMI B6
#define CTRL B3
#define RAMI B2

#define LAYOUT( \
    K00, K01, K02, K03,   \
    K10, K11, K12, K13,   \
    K20, K21, K22, K23,   \
    K30, K31, K32, K43,   \
    K41,      K42         \
) { \
    { K00,   K01,   K02,   K03   }, \
    { K10,   K11,   K12,   K13   }, \
    { K20,   K21,   K22,   K23   }, \
    { K30,   K31,   K32,   KC_NO }, \
    { KC_NO, K41,   K42,   K43   }, \
}

#define AKC_RST_WARN 0x78

// generated by KBFirmware JSON to QMK Parser
// https://noroadsleft.github.io/kbf_qmk_converter/
